export const DOMAINS = () => ({
  SEARCH_SERVICE: process.env.SEARCH_SERVICE,
  PLATFORM_SERVICE: process.env.PLATFORM_SERVICE,
  CMS_SERVICE: process.env.CMS_SERVICE,
  ADDRESS_SERVICE: process.env.ADDRESS_SERVICE,
  RFQ_SERVICE: process.env.RFQ_SERVICE,
  RFQ_API_SERVICE: process.env.RFQ_API_SERVICE
});
